//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Radial_Distribution_System_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class buses
    {
        public int busID { get; set; }
        public int feederId { get; set; }
        public string type { get; set; }
        public Nullable<double> voltage { get; set; }
        public Nullable<double> frequency { get; set; }
        public string insulation { get; set; }
        public string Zs { get; set; }
        public string Zm { get; set; }
        public string Ys { get; set; }
        public string Ym { get; set; }
        public Nullable<double> length { get; set; }
        public string Ztr { get; set; }
        public Nullable<double> VArate { get; set; }
        public string cooling { get; set; }
        public Nullable<double> primaryvoltage { get; set; }
        public Nullable<double> secondaryvoltage { get; set; }
        public string connectiongroup { get; set; }
        public string primaryconnection { get; set; }
        public string secondaryconnection { get; set; }
    }
}
