//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Radial_Distribution_System_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feeder
    {
        public int feederID { get; set; }
        public string Fname { get; set; }
    }
}
