//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Radial_Distribution_System_2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PMUEntities1 : DbContext
    {
        public PMUEntities1()
            : base("name=PMUEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Feeder> Feeder { get; set; }
        public virtual DbSet<Phase1> Phase1 { get; set; }
        public virtual DbSet<Phase2> Phase2 { get; set; }
        public virtual DbSet<Phase3> Phase3 { get; set; }
        public virtual DbSet<buses> buses { get; set; }
    }
}
