//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Radial_Distribution_System_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phase3
    {
        public int ID { get; set; }
        public int busID { get; set; }
        public int feederid { get; set; }
        public System.DateTime dataTime { get; set; }
        public Nullable<double> VhM { get; set; }
        public Nullable<double> VhA { get; set; }
        public Nullable<double> VlM { get; set; }
        public Nullable<double> VlA { get; set; }
        public Nullable<double> IhM { get; set; }
        public Nullable<double> IhA { get; set; }
        public Nullable<double> IlM { get; set; }
        public Nullable<double> IlA { get; set; }
        public Nullable<double> ph { get; set; }
        public Nullable<double> Qh { get; set; }
        public Nullable<double> Pl { get; set; }
        public Nullable<double> Ql { get; set; }
        public Nullable<double> Plosscable { get; set; }
        public Nullable<double> Qlosscable { get; set; }
        public Nullable<double> Plosstr { get; set; }
        public Nullable<double> Qlosstr { get; set; }
    }
}
